const TaskDescription = () => {
  return (
    <div className="task-description">
      <h2>🖋️ Poetry task</h2>
      <h3>📜 Rules</h3>
      <ol>
        <li>Give the theme of the poem to the AI to get started. After that, the first line will be generated by the AI</li>
        <li>You and the AI take turns to write the poem</li>
        <li>There are two input field: the first one is for adding a new poem line, the second one is for chatting with the AI</li>
        <li>The poem is finished when it reaches the 9-line limit</li>
      </ol>
    </div>
  );
};

export default TaskDescription;
